### ISSUE TITLE
Search results show "0 subscribers" for all channels

### ISSUE THREAD

**Issue by JustAnotherArchivist** [omarroth/invidious#753]
It seems that Invidious always displays "0 subscribers" now on search results. The subscription button on the channel page still shows the correct number, and those channels' subscription count is not hidden (i.e. this is not the same as #459). YouTube recently started hiding the exact subscription count (cf. [here](https://twitter.com/SocialBlade/status/1172262965380358144) and [here](https://twitter.com/SocialBlade/status/1171211093311705088)), which I guess might be the reason for this. I haven't seen it happening before.

Example: https://invidio.us/channel/UC7_gcs09iThXybpVgjHZ_7g shows up as "0 subscribers"  (instead of "1.7M subscribers") on https://invidio.us/search?q=pbs+space+time

**Comment by omarroth** [comment]
Thanks for making an issue here. This has been mentioned in the Matrix Server and is indeed related to  abbreviated subscriber counts. YouTube's announcement is [here](https://support.google.com/youtube/thread/6543166).

Channel subscriber counts are already fixed with b1fc80b79ae498f7bfd6ad7a32ebee98fabdaf4a. Search will need to be rewritten to support YouTube's new polymer design, since the endpoint Invidious currently uses no longer provides subscriber counts:

![image](https://user-images.githubusercontent.com/14208607/64910857-1f28c380-d6e9-11e9-9622-fc774dac7964.png)

Which unfortunately will take more time.

**Comment by Z3ROGRAV1TYx** [comment]
Just a reminder that thsi issue still persists.
[Another example screenshot.](https://b.catgirlsare.sexy/0Qsy.png)

**Comment by materthewelon** [comment]
will this get fixed on invidio.us

**Comment by omarroth** [comment]
Should be fixed as part of 1eca969cf6b4096789014619285c98d1def40ee3.

**Comment by unixfox** [comment]
Yes it's fixed.
